-- 꼭 VO와 DB테이블 갯수가 일치하지 않아도 된다.
-- 고객은 패스워드가 필요없다 의사만 패스워드가 필요하다.

CREATE TABLE CUSTOMER(
    CLNUMBER NUMBER PRIMARY KEY, -- 고객번호
    CLNAME VARCHAR2(30) NOT NULL, --고객이름
    CLPN VARCHAR2(30) NOT NULL, --고객주민번호
    CLPHONE VARCHAR2(30) NOT NULL --고객 전화번호
);


CREATE TABLE DOCTOR(
    DONUMBER NUMBER PRIMARY KEY, --의사번호
    PARTNUMBER NUMBER REFERENCES PART(PARTNUMBER), --부서번호
    DONAME VARCHAR2(30), -- 의사이름
    PASSWORD VARCHAR2(30), --비밀번호
    INFO_DOCTOR VARCHAR2(30), --의사정보
    PARTNAME VARCHAR2(30)--부서명
);



CREATE TABLE PART(
    PARTNUMBER NUMBER PRIMARY KEY,  --부서번호
    PARTNAME VARCHAR2(30) --부서명
);


CREATE TABLE RESERVE(
    RENUMBER NUMBER, --예약번호
    CLNUMBER NUMBER REFERENCES CUSTOMER(CLNUMBER), --고객번호
    CLNAME VARCHAR2(30) REFERENCES CUSTOMER(CLNAME), --고객이름
    CLPN VARCHAR2(30) REFERENCES CUSOTMER(CLPN), --고객 주민번호
    SYMPTOM VARCHAR2(30), --증상
    PARTNUMBER NUMBER , --부서번호
    SCHEDULE DATE,  --예약날짜
    DONUMBER NUMBER, --의사번호
    DONAME VARCHAR2(30) -- 의사이름
);
