CREATE TABLE CLIENTS (
 CLNUMBER NUMBER PRIMARY KEY,
 CLNAME VARCHAR2(30) NOT NULL,
 CLPN VARCHAR2(30) NOT NULL,
 CLPHONE VARCHAR2(30) NOT NULL
 );

CREATE TABLE RESERVE (
 RENUMBER INT PRIMARY KEY,
 CLNUMBER NUMBER NOT NULL,
 SYMPTOM VARCHAR2(30) NOT NULL,
 SCHEDULE DATE NOT NULL,
 DONUMBER NUMBER NOT NULL
);
 
 
CREATE TABLE DOCTOR (
 DONUMBER NUMBER PRIMARY KEY,
 PARTNUMBER NUMBER NOT NULL,
 DONAME VARCHAR2(30) NOT NULL,
 PASSWORD VARCHAR2(30) NOT NULL,
 INFO_DOCTOR VARCHAR2(100) NOT NULL
 );
 

CREATE TABLE PART (
 PARTNUMBER NUMBER PRIMARY KEY,
 PARTNAME VARCHAR2(100) NOT NULL
 );
 
 COMMIT;
 
 
ALTER TABLE RESERVE
ADD CONSTRAINTS FK_1 FOREIGN KEY(CLNUMBER)
REFERENCES CLIENTS(CLNUMBER);


ALTER TABLE RESERVE
ADD CONSTRAINTS FK_2 FOREIGN KEY(DONUMBER)
REFERENCES DOCTOR(DONUMBER);

ALTER TABLE DOCTOR
ADD CONSTRAINTS FK_3 FOREIGN KEY(PARTNUMBER)
REFERENCES PART(PARTNUMBER);

COMMIT;




-- Clients, Doctor, Reserve table sequence »ý¼º. 
CREATE SEQUENCE CLIENTS_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE DOCTOR_SEQ
START WITH 10001
INCREMENT BY 1; 

CREATE SEQUENCE RESERVE_SEQ
START WITH 1
INCREMENT BY 1; 
COMMIT;

